### ISSUE TITLE
Search across all scripts

### ISSUE THREAD

**Issue by G2H** [dataform-co/dataform-tracking#100]
Allow searching across all the files names and content in a project.
The page should return a list of files with a snippet of their content where the search term is highlighted

A search and replace function could also be added

---
Moved from tada-science/dataform-co#159
/cc @G2H

**Comment by lewish** [comment]
This was discussed recently:

- Behaviour should be similar to the existing file search, using the spotlight blueprint components.
- Think it would be fine to do this entirely client side, and make sure we fetch all files when we load up a project into the global store.

**Comment by GJMcGowan** [comment]
To do this, probably best to have some better client side storage available.

Aim to add a simple redux implementation beforehand which stores the file contents.

Structure should be something like 
```
  {
    "projectId": {
       "workspaceId": {
          "files": {...}
        }
    }
  }
```

**Comment by GJMcGowan** [comment]
Redux store could maybe include user data, project settings etc. but that can be added later from the old store.

**Comment by GJMcGowan** [comment]
Mockup of what the search page should roughly look like: https://www.figma.com/file/T6ZZuZYmfFKr80eXiyhhDAD3/Onboarding%2C-blog%2C-search-and-catalog?node-id=55%3A0

Requirements (not set in stone, iterate on them):
* Add link in existing search modal to "search within files", alongside the simple file list search
* Add a dedicated search page with following features:
  * Search field, pre-populated with search query from modal (editable)
  * Full list of all files that match the search query, and all places in that file that match the query
  * Shows 2 lines above/below the line with the query in the file
  * Highlights where the query is in some way
  * Includes metadata: filename, file type, path.
  * Presume clicking on a file name should take you to that file.
