### ISSUE TITLE
All warehouses disconnected

### ISSUE THREAD

**Issue by acabaniss** [dataform-co/dataform-tracking#299]
Starting at about 10 am EDT today, all of my warehouses have disconnected across ~6 projects and are no longer appearing in Dataform. Further, that part of the UI doesn't load (it stays a spinning circle), so there is no way to add new credentials.

**Comment by BenBirt** [comment]
Apologies for this, we're aware of the issue - fix is on its way.

**Comment by BenBirt** [comment]
Fix has been pushed.
