### ISSUE TITLE
Separate run environment for develop and master branches. 

### ISSUE THREAD

**Issue by ghost** [dataform-co/dataform-tracking#305]
At our organization we have separate development and production GCP projects. Dataform would work better if I could set the default project and dataset for master and develop branches. 
I am aware of the "configOverride" in the environments.json file [as shown here](https://docs.dataform.co/dataform-web/scheduling/environments#example-use-separate-databases-for-development-and-production-data]), but that only covers the scheduler and not the manual runs I can do by clicking on "Start New Run".

**Comment by BenBirt** [comment]
In this case I'd propose configuring the defaults in `dataform.json` to be your development environment. Production runs will happen from the overrides as specified in `environments.json`.
