### ISSUE TITLE
"Push to Master" gone

### ISSUE THREAD

**Issue by georgelee-parsleyhealth** [dataform-co/dataform-tracking#306]
Recently I have been trying to push my commits to the master branch I get a "Open Pull Request on Github.com". The usual "Push to Master" isn't there. With the "Open Pull Request on Github.com" option I have to pull and merge, more clicks then I would like to make. How do I get back the "Push to Master"?

<img width="552" alt="image" src="https://user-images.githubusercontent.com/84410634/123439200-7a1a6a80-d59f-11eb-82b5-8832aaba47ca.png">

**Comment by BenBirt** [comment]
It sounds like somebody has configured your project to push to non-`master` branches. Check the "Require pull requests for all changes" setting in Project Settings.
