### ISSUE TITLE
Error 503, no healthy upstream on API triggered runs

### ISSUE THREAD

**Issue by mrossero** [dataform-co/dataform-tracking#325]
Hello,
as per title, in the last two days I get Error 503 (no healthy upstream) when trying to trigger runs through API. This is happening on two of my projects (one of which isn't receiving configuration changes since a month ago, so I tend to exclude this is due to changes on my part). When I trigger the run from the interface, it works just fine. 

Are there currently server problems?

**Comment by ttjmartinez** [comment]
I'm seeing the same problem in my two projects since yesterday, I trigger the run from the API and it completes successfully, but the HTTP response for that API call is Error 503, no healthy upstream.

The first time I saw the problem was Feb 13, 2022 1:14:33 AM UTC

**Comment by mrossero** [comment]
as of February 21th the problem seems to be solved, still I would like to know what caused it and (expecially) if we can expect to see it again.

**Comment by sidakaboney23** [comment]
Does anyone know why it was caused? I have a similar issue stating a lack of upstream availability?

**Comment by mrossero** [comment]
> Does anyone know why it was caused? I have a similar issue stating a lack of upstream availability?

No, I think it's related to Dataform being acquired by Google and being integrated into GCP. I contacted them some time ago and they basically told me that Dataform legacy (the standalone version) will not receive fixes because they will focus on the GCP version. It may be a good idea to perform a migration to Dataform GCP, if you can.
