### ISSUE TITLE
Dataform schedules didn't run in the last night (at least between 22:30 and 00:30 UTC)

### ISSUE THREAD

**Issue by HolgerZschaebitz** [dataform-co/dataform-tracking#335]
We have four schedules defined which ran perfectly in the past but not during the last night.
1) What happened?
2) What is done to prevent this in the future?

**Comment by BergQ** [comment]
Same problem here and same questions as @HolgerZschaebitz. 

Our schedules are supposed to start right after midnight. Two days ago the runs started at 12:06 PM and today at 11:20 AM.

**Comment by HolgerZschaebitz** [comment]
I received the following answer from Dtaform's support:
"We are aware of this problem and our engineering team has confirmed that it has been addressed. They are looking for the reason for the crash to hopefully avoid a recurrence. All operations scheduled during this period of unavailability should have started now. Please check and let us know if there is still a problem with the scheduler.
However, Please be aware that legacy Dataform has no SLA/SLO now. So the best thing to do is to move to GCP Dataform which is now available in GA."
