### ISSUE TITLE
Support pushing a workspace/branch to a new branch in git and creating a PR

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform-tracking#88]
Currently all branches get pushed straight to `master`. It should be possible to push to a new branch in github instead, and have the option to create a PR (although this could be done in github for now).

**Comment by lewish** [comment]
Some thoughts:

Once a new branch / PR is created, that branch should continue to track the new branch until it's merged back into master, or when the user chooses to do so.

We need to expose this information about the remote tracking branch to the user.

This should only be possible for GitHub linked projects.

We will need a way in general to change the remote tracking branch of any individual branch in data form.

**Comment by BenBirt** [comment]
Done!
